spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DBMS_CONNECTION:jdbc:mysql://10.8.0.1:3308/xe_dap}
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:123}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

server:
  port: 5555